dataset:
  max_cands: 20
  data_dir: /home/laurits/0422_high_pt_samples/
  # data_dir: /scratch/persistent/laurits/ml-tau/0412_increased_stats/
  relative_sizes:
    train: 0.7
    val: 0.1
    test: 0.2
